### ISSUE TITLE
The sample animation exported with Flash2SVG works on Chrome but not on Safari

### ISSUE THREAD

**Issue by Emasoft** [TomByrne/Flash2Svg#12]
The sample exported animation that you provided works on Chrome but not on Safari. It runs but the playback stutters and no audio.

http://www.tbyrne.org/portfolio/smil/LoveDota.svg

Is this a known issue?

**Comment by TomByrne** [comment]
Unfortunately playback performance is in the hands of the browser vendor.
Also, this demo SVG was intentionally constructed to push the limits of what browsers might be able to handle, so I'm not really surprised that performance suffers in Safari.

That said, there have been 23 versions since the one used to create that demo, so potentially newer versions will produce a more performant SVG, although I wouldn't expect more than a 10% improvement in performance (probably more of an improvement in file size).

**Comment by Emasoft** [comment]
I don't think it is a performance issue. I've checked cpu usage during playback and it is very low (one core used, at 30%). Also on the same machine with the Chrome browser it works perfectly and animations are very smooth.
I think it is more likely caused by some bug in the Safari implementation of the SMIL standard. You should isolate the problem and report it to Apple, or write a workaround.
