### ISSUE TITLE
animations in symbols are looping permanently 

### ISSUE THREAD

**Issue by 1GR3** [TomByrne/Flash2Svg#38]
I've added:
this.stop()
but in exported svg the symbols are looping forever.

**Comment by jarkkosyrjala** [comment]
I believe this is expected behaviour for a MovieClip - no scripting is supported. Try converting you symbol to a Graphic symbol. Then you should have an option to either loop it or play it once.

**Comment by 1GR3** [comment]
I have multiple instances of that specific symbol on the various frames in the root timeline. I made a workaround by expanding the last frame beyond the length of the root and unchecking the loop in export.
Example:
http://liberland.sinmc.org/images/hero.svg
as you might see, the last building didn't get the last row of windows because the root timeline is too short but it took dozens of minutes to render it so I'll leave it as it is for now :)

**Comment by TomByrne** [comment]
As mentioned above, script added to the Actionscript panel won't have any effect in SVG, all actionscript is completely ignored during export.

Due to the way SVG is, child animations that are reused like this (i.e. with different start times) can only really be achieved by creating separate frames of the subanimation and manually showing and hiding these frames in the parent animation (which is what your hero.svg animation is doing, as you've selected Graphic on the child animation).

This makes the resulting SVG much bigger than if the actual nested timeline was retained, as happens when you select MovieClip for a child animation, but then the nested children will all start at the same time and will loop indefinitely.

**Comment by 1GR3** [comment]
I tried to increase the length and rearrange the order of layers but after 2 and a half hours of exporting it failed... any plans to support scripting in the future?

**Comment by TomByrne** [comment]
Not really, Animate already has several JS based export options, the point of the SVG export is that it doesn't depend on any scripting. You should check out the 'HTML Canvas' and 'WebGL' document types, they'll be way more fully featured than this plugin (and I believe support javascript from within the 'Actions' panel).

You can copy/paste your timelines from a Flash document into these other document types.

**Comment by 1GR3** [comment]
I'm aware of 'HTML Canvas', 'WebGL' and SnapSVG export methods and none of them really beats the swf. Canvas and WebGL are not really scalable (they're pixelated and scripting in not always working) and SnapSVG just like Bodymovin exports json file that has to be interpreted by js player to create an SVG on the flay. Replacing swf with SVG in export seems like the smoothest way of using Animate in the non-flash-player web. SVG supports embedding JS for interactions so I would really appreciate if Flash2SVG would allow at least basic interactions.

**Comment by TomByrne** [comment]
the problem here is that Flash2Svg doesn't control the playback of the animations, it's all taken care of by the underlying SMIL framework. The controls that SMIL offers are very limited, with only one JS method to call (beginElement).

It's designed as a declarative animation system, which (once playing) isn't really interactive.

So there's no way I can convert 'stop()' to any equivilant in JS.

It could be done by building an abstraction layer on top of SVG/SMIL which keeps track of which elements are part of which timelines, but this is tons of work and is essentially what SnapSVG have already done.

**Comment by ROBERT-MCDOWELL** [comment]
Tom, I don't know if this discussion can help
https://stackoverflow.com/questions/5378559/including-javascript-in-svg
I think users just need (again) a recurrent AS to JS converter ;)

**Comment by TomByrne** [comment]
Converting the AS to JS won't actually help, as there aren't the same underlying functions to call in SVG/SMIL. If you want this functionality you need the animation to be totally controlled by JS.
There's actually no point in adding this functionality to Flash2Svg, as the end result will be pretty much the same as SnapSVG (and it would take weeks to actually build).
