### ISSUE TITLE
Flickering on hover

### ISSUE THREAD

**Issue by 1GR3** [TomByrne/Flash2Svg#39]
I tried to animate icons on hover. Changing background images in CSS worked only the first time (unless the animation is looping) so I'm using this JS:

       $("a.some-icon").hover(function(){
	        $(this).find("img").attr("src","animated.svg");
        })
        $("a.some-icon").mouseout(function(){
	        $(this).find("img").attr("src","static.svg");
        })

but it is not completely smooth... Any other suggestions?

**Comment by TomByrne** [comment]
Yeah, I'm not sure.
I think that loading in a new resource like this will always cause some flicker, as the browser will take a little time to load the asset from the cache and rebuild the elements. I'd probably approach it by loading both in and changing their visibility based on rollover/rollout, although you'll need to manually control the playback of the svg animation then.

I'm sure there would be a way to do this in pure SVG, similar to the ones on this page:
http://www.tbyrne.org/viber-animated-svgs

**Comment by 1GR3** [comment]
Very impressive! But it works on click. Any idea how did Viber's team achieve that?

**Comment by TomByrne** [comment]
I made those animations for Viber using Flash2Svg (with the Begin Animation > on Click option).
You can change the event type used by doing a find and replace on the SVG file (i.e. change 'click' to 'mouseover').

The problem is that the mouseover event gets fired every time the mouse passes over a new element in the document, meaning the animation keeps restarting while it's playing (as different elements move under your mouse).

The workaround for this is to add a transparent rectangle over everything and use that as the event dispatcher.

I've attached a file with these changes to show how this can be achieved (you'll need to rename it to 'svg').
[Animation.svg.txt](https://github.com/TomByrne/Flash2Svg/files/1614056/Animation.svg.txt)

**Comment by 1GR3** [comment]
Thank you, I'll definitely consider this approach too!
I assume it won't support that method of in and out animations:

on(mouseOut).function(){
     gotoAndPlay(totalframes-_currentframe);
}

(I don't really remember AS syntax but that's the main idea)
 O gosh, all these workarounds just make me miss Flash even more :(

**Comment by ROBERT-MCDOWELL** [comment]
Lol, stay involved, flash always been the most advanced and clean web tech.
a lot of long running developers decided to fuck off javascrap spaghetti and work actively to silently switch swf work into the next. btw flash is still much more quality than the rest. it's like compare an  Organic to GMO food...
