### ISSUE TITLE
Can't revert document, please deselect revert or use a revertable document

### ISSUE THREAD

**Issue by stkopp** [TomByrne/Flash2Svg#9]
![](http://i.imgur.com/JxKZEAM.png)

**Comment by TomByrne** [comment]
Did you try and deselect revert with the drop down directly below the publish button?

**Comment by stkopp** [comment]
Sorry, I forgot to save my work before exporting.

**Comment by gludion** [comment]
I have version 3.45.0 of this extension + flash CC 2014 and have the same problem. Tried to select "no-save, no revert" but the popup still shows up.

**Comment by TomByrne** [comment]
Are you able to retry with the latest version?
If it is a HTML document it isn't supported BTW.

**Comment by TomByrne** [comment]
Can you send me the document you're using?
By the way, it won't work with an HTML document.

**Comment by keithpickering** [comment]
Experiencing the same issue - tried with both HTML5 and Actionscript. Just doesn't work.

**Comment by TomByrne** [comment]
Hey guys,
The revert/save options were originally added to get around an issue which is no longer relevant.
I've removed the option for now, looks like it may not have been behaving as expected through the HTML UI.
Version 3.46 will have this feature removed, which should let you use the tool as expected.

**Comment by gludion** [comment]
installed 3.46.0, still have the issue. 
- create new flash file
- open "SVG animation" panel, observe that "save & revert" etc. options are indeed no longer in combo box
- draw circle in scene
- save file in a directory
- click "export" 
  => dialog: "can't revert document, please deselect revert or use a revertable document"

**Comment by TomByrne** [comment]
Please try with v3.47 and let me know how you go.

**Comment by gludion** [comment]
hello, and thanks for your quick update.
no more "can't revert document etc" => fine!

However, I've another issue when I click on "export":
- the extension creates a bunch of new symbols, sub-directories around the FLA file, an HTML page which deceptively displays the correct animations (but it's actually displaying the original SWF file using flash plugin), a CSV log, etc..
- output displays: "TypeError: svgXml.defs[0] is undefined"
- no SVG in sight :(

I'm afraid I may not test further updates, because I've found another extension which perfectly suits my needs:
https://nipunasthana.wordpress.com/2014/11/30/export-svg-sequence/

**Comment by ahbox** [comment]
Had the issue and after installing 3.47 everything rocks! Very great extension.

**Comment by TomByrne** [comment]
Hey gludion, if you send me your FLA I can take a look. Also, what version of Flash/Animate are you using.
